font:
  dir: ~/UbuntuMono-R.ttf
  size: 15
  title_size: 13
screen_size:
  width: 96
  height: 200
page_size: 13
music:
  directory:
    - ~/Music/
  library: library.sqlite
  buffer_load_size: 10
  bad_tracks:
    - 112
colors:
  white: 1
  black: 0
buttons:
  up: 26
  down: 19
  select: 20
  play: 16
  volume: 21
